###################################################################################################################
##
## coredns安装文件，默认安装到kube-system命名空间中
## 外部需要替换一下几个参数：
## ${VIP_CIDR}: K8S的service ip的范围，例如194.10.0.0/16
## ${POD_CIDR}: pod的ip范围，例如193.0.0.0/8
## ${CLUSTER_DOMAIN}: K8S集群的域名后缀，注意，这个域名只会使用K8S解析，不会转发到其他地方；例如 kube.local
## ${DNS_TTL}: 响应给dns查询客户端的ttl，例如30，表示30秒
## ${PROMETHEUS_PORT}: Prometheus的端口号，例如9253
## ${UPSTREAMNAMESERVER}: 域名服务器（也可以是文件，例如/etc/resolv.conf），对于coredns无法解析的域名转发到该服务器解析；
## ${CLUSTER_DNS_IP}: dns在集群中的service ip
##
###################################################################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system


---

# kubernetes插件文档：https://coredns.io/plugins/kubernetes/
# hosts插件文档：https://coredns.io/plugins/hosts/
# 下面指定的errors、health等都是插件名，注意插件有顺序
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  # coredns配置，
  Corefile: |
    # K8S域名解析走这里，配置vip CIDR 和 pod的CIDR来允许对这两个ip段进行dns反解析
    ${CLUSTER_DOMAIN} ${VIP_CIDR} ${POD_CIDR} {
        errors
        health {
          lameduck 5s
        }
        ready
        # 注意这里不用配置fallthrough，因为K8S集群的域名只有K8S能解析，其他解析不了
        kubernetes ${CLUSTER_DOMAIN} ${VIP_CIDR} ${POD_CIDR} {
          # pods有三种模式：
          # 1、disabled：不处理pod的请求，永远返回域名不存在；
          # 2、insecure：如果coredns中存在指定pod的A record（即域名与IP的映射关系）则返回；
          # 3、verified：会验证请求对应的A record指向的pod是否与发起请求的pod在同一个namespace，如果在则返回，否则返回查找不到（这个没有验证，官网大概是这个意思）
          pods insecure
          # 响应给dns查询客户端的ttl
          ttl ${DNS_TTL}
        }
        prometheus :${PROMETHEUS_PORT}
        cache 30
        # 允许动态更新Corefile的该部分，10秒检测一次配置文件变更
        reload 10s
        loadbalance
    }
    # 非K8S的域名走这里
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        # 先走自定义的host文件，配置fallthrough，如果host文件中没有定义继续往下
        hosts /etc/coredns/hosts {
          ttl ${DNS_TTL}
          # N秒检测一次hosts文件有没有变更，这个时间已经够了，因为这个文件是通过configmap挂载过来的，configmap变更同步还需要一段时间；
          reload 30s
          fallthrough
        }
        prometheus :${PROMETHEUS_PORT}
        forward . ${UPSTREAMNAMESERVER} {
          max_concurrent 1000
        }
        cache 30
        # 静态检测循环查询，例如coredns将查询转发给本地127.0.0.1，然后127.0.0.1又将查询转发给了coredns，如果发现这种链路将动态将该链路删除；
        loop
        # 允许动态更新Corefile的该部分，10秒检测一次配置文件变更
        reload 10s
        loadbalance
    }
  # 全局host映射配置，这里可以添加其他的一些配置
  Hosts: |
    127.0.0.1 localhost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: "CoreDNS"
spec:
  # replicas: not specified here:
  # 1. Default is 1.
  # 2. Will be tuned in real time if DNS horizontal auto-scaling is turned on.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                   - key: k8s-app
                     operator: In
                     values: ["kube-dns"]
               topologyKey: kubernetes.io/hostname
      containers:
      - name: coredns
        image: coredns/coredns:1.8.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: ${PROMETHEUS_PORT}
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
            - key: Hosts
              path: hosts
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "${PROMETHEUS_PORT}"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: ${CLUSTER_DNS_IP}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: ${PROMETHEUS_PORT}
    protocol: TCP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  entryPoints:
    - dns
  routes:
    - services:
        - name: kube-dns
          port: 53

