###################################################################################################################
##
## 监控安装，会安装grafana、Prometheus等
##
## 需要全局替换以下参数：
## ${etcdAddr}: etcd地址，存储数据用，例如192.168.1.1:2379，如果有多个（集群），多个地址以逗号分割；
## ${kuboardHost}: kuboard的ingress地址，例如kuboard.kube.com
##
## kuboard安装完毕后需要进入页面，然后获取agent安装脚本，将agent安装到集群中才算安装完毕；注意：获取agent脚本的链接
## 中的域名要替换为对应的kuboard的service的IP
## 
## 
###################################################################################################################


---
apiVersion: v1
kind: Namespace
metadata:
  name: kuboard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuboard-v3-config
  namespace: kuboard
data:
  # 关于如下参数的解释，请参考文档 https://kuboard.cn/install/v3/install-built-in.html
  # [common]
  # webui，kuboard-agent通过该地址访问kuboard
  KUBOARD_ENDPOINT: 'http://kuboard-v3'
  KUBOARD_AGENT_SERVER_UDP_PORT: '10081'
  KUBOARD_AGENT_SERVER_TCP_PORT: '10081'
  # error / debug / trace
  KUBOARD_SERVER_LOGRUS_LEVEL: info
  # KUBOARD_AGENT_KEY 是 Agent 与 Kuboard 通信时的密钥，需要是任意的包含字母、数字的32位字符串，此密钥变更后，需要删除 Kuboard Agent 重新导入。
  KUBOARD_AGENT_KEY: 456151sdf65761sdlfiklhjliulknlnw

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '9'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/workload: kuboard-v3
  labels:
    k8s.kuboard.cn/layer: ''
    k8s.kuboard.cn/name: kuboard-v3
  name: kuboard-v3
  namespace: kuboard
spec:
  # 注意，这里只能是1个副本，后续kuboard升级可能会支持多副本
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: ''
      k8s.kuboard.cn/name: kuboard-v3
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: ''
        k8s.kuboard.cn/name: kuboard-v3
    spec:
      containers:
        - env:
            - name: KUBOARD_ETCD_ENDPOINTS
              value: >-
                ${etcdAddr}
          envFrom:
            - configMapRef:
                name: kuboard-v3-config
          image: 'swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard:v3'
          imagePullPolicy: Always
          name: kuboard

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: kuboard-v3
  labels:
    k8s.kuboard.cn/layer: ''
    k8s.kuboard.cn/name: kuboard-v3
  name: kuboard-v3
  namespace: kuboard
spec:
  ports:
    - name: webui
      port: 80
      protocol: TCP
      targetPort: 80
    - name: agentserverudp
      port: 10081
      protocol: UDP
      targetPort: 10081
  selector:
    k8s.kuboard.cn/layer: ''
    k8s.kuboard.cn/name: kuboard-v3
  sessionAffinity: None
  type: ClusterIP

---
# 创建一个中间件，将自动添加ContentType的功能关闭（注意，该中间件如果要使用请手动添加到IngressRoute定义中）
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: autodetect
  namespace: kuboard
spec:
  contentType:
    autoDetect: false

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kuboard-v3
  namespace: kuboard
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`${kuboardHost}`)
    kind: Rule
    services:
    - name: kuboard-v3
      port: 80
    # 中间件
    middlewares:
    - name: autodetect